# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Capture Schedule

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/15 * * * *"
    # Run every 15 mins.

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run capture
# Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "ashleykolodziej"
        git config --global user.email "kindle-status[bot]@ashleykolodziej.github.io"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Capture file created.' || echo
        git push
